name: Terraform
on:
  workflow_dispatch:
jobs:
  terraform:
    name: Terraform
    env:
      AWS_ACCESS_KEY: ${{ secretes.AWS_DEVOPS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ AWS_DEOPS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Terraform Init
        uses: hashicorp/terraform-github-action@master
        with: null
        tf_actions_version: 0.14.3
        tf_actions_subcommand: itit
        tf_actions_working_dir: .
        tf_actions_comment: true
      - name: Terraform plan
        uses: hashicorp/terraform-github-action@master
        with: null
        tf_actions_version: 0.14.3
        tf_actions_subcommand: plan
        tf_actions_working_dir: .
        tf_actions_comment: true
      - name: Terraform apply
        uses: hashicorp/terraform-github-action@master
        with: null
        tf_actions_version: 0.14.3
        tf_actions_subcommand: apply
        tf_actions_working_dir: .
        tf_actions_comment: true
